config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post '/users/mobile_sign_in', to: "users/sessions#mobile_login"
    post '/users/mpin_sign_in', to: "users/sessions#mpin_login"
    get '/users/get_organisations', to: "users/sessions#get_organisations"
    post '/users/mobile_sign_up', to: "users/registrations#create_mpin"
    post '/users/register_notification', to: "users/registrations#register_notification"
  end
  
  devise_for :users,
  controllers: {
    invitations:   'users/invitations',
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    unlocks:       'users/unlocks',
    registrations: 'users/registrations'
  },skip: [:confirmations] 

  
  devise_for :organisations,
  controllers: {
    sessions:      'organisations/sessions'
  },
  skip: [:confirmations]
  
  resources :register_organisations do
    member do 
      get :sms_confirmation
      post :verify_confirmation
    end
  end

  resources :sms_sent, only: [:index]

  resources :parents_meetings, only: [:index, :new, :create, :show] do
    member do
      get :publish_meeting
      get :get_meeting_students
    end
    collection do 
      get :get_class_students
    end
  end
  
  resources :questions, only: [:index, :show] do
    collection do 
      get :filter_info
    end
  end
  
  

  as :user do
    post 'users/reset_password', to: "users/passwords#create", as: 'user_password_reset'
  end

  resources :exams, only: [:index] do 
    collection do 
      get 'calender_index'
      get 'get_filter_data'
    end
  end

  resources :off_classes, only: [:index] do 
    collection do 
      get 'calender_index'
      get 'get_filter_data'
    end
  end
  
  resources :students, except: [:update] do
    member do
      get 'download_report'
      get 'get_graph_data'
      get 'get_fee_info'
      get 'get_payments_info'
      get 'get_hostel_info'
      get 'get_absentee'
      get 'get_clearance'
      get "get_exams"
      post 'paid_student_fee'
      post 'update'
      post 'toggle_sms'
      post 'allocate_hostel'
      post 'upload_photo'
      delete 'deallocate_hostel'
    end
    collection do 
      get 'get_filter_values'
      get 'sync_organisation_students'
    end
  end

  resources :standards, only: [] do
    member do
      get 'optional_subjects'
    end
  end

  resources :student_fees, only: [:index] do
    member do
      get 'print_receipt'
    end
    
    collection do
      get 'get_logs'
      get "filter_data"
      get "graph_data"
      get 'print_account'
      get "download_excel"
      get "/:jkci_class_id/get_transactions/:student_id" => "student_fees#get_transactions"
    end
  end
  
  
  get "get_unassigned_classes" => "jkci_classes#get_unassigned_classes"
  get "sub_organisation/:sub_organisation_id/class/:jkci_class_id/get_report" => "jkci_classes#sub_organisation_class_report", as: "sub_organisation_class_report"
  get "/class/:id/sub_class_students_report" => "jkci_classes#sub_class_students_report", as: "sub_class_students_report"
  get "/class/:id/download_class_catlog" => "jkci_classes#download_class_catlog", as: "download_class_catlog"
  get "/class/:id/download_class_student_list" => "jkci_classes#download_class_student_list", as: "download_class_student_list"
  get "/class/:id/download_class_syllabus" => "jkci_classes#download_class_syllabus", as: "download_class_syllabus"
  get "/classes/:id/download_excel" => "jkci_classes#download_excel"

  scope '/organisations' do
    resources :teachers do
      member do
        get :get_remaining_subjects
        get :save_subjects
        get :get_subjects
        get :get_time_table
        get "subjects/:subject_id/remove" => "teachers#remove_subjects"
      end
    end
    resources :user_clerks, only: [:edit, :update, :destroy] do
      member do
        get :resend_invitation
      end
    end
  end
  
  resources :teachers, only: [] do
    member do
      get :get_subjects
      get :daily_teachs
    end
  end

  resources :vendors do
    resources :vendor_transactions
    collection do
      get :get_logs
    end
  end
  
  resources :jkci_classes do
    member do
      get 'presenty_catlog'
      get 'download_presenty_catlog'
      get 'get_exam_info'
      get 'get_activities'
      get 'get_activity'
      get 'get_dtp_info'
      get 'toggle_class_sms'
      get 'toggle_exam_sms'
      get 'assign_students'
      get 'students'
      get 'check_verify_students'
      get 'get_chapters'
      get 'manage_student_subject'
      get 'manage_roll_number'
      get 'get_notifications'
      get 'get_timetable'
      get 'get_time_table_to_verify'
      get 'get_batch'
      get 'get_subjects'
      get 'get_time_table'
      post "import_students_excel"
      post 'make_active_class'
      post 'make_deactive_class'
      post 'verify_students'
      post 'recheck_duplicate_student'
      post 'accept_duplicate_student'
      post 'save_student_subjects'
      post 'manage_students'
      post 'save_roll_number'
      post 'upgrade_batch'
    end
    collection do 
      get :sync_organisation_classes
      get :sync_organisation_class_students
    end
    
    resources :sub_classes, only: [:index, :create, :show, :destroy] do
      member do
        get 'students'
        get 'remaining_students'
        get 'get_time_table'
        post 'add_students'
        delete 'remove_student/:student_id' , to: "sub_classes#remove_student"
      end
    end
    
    resources :time_tables, only: [:index, :create, :show]
    
    resources :daily_teachs, except: [:update] do
      member do
        get 'get_catlogs'
        get 'class_absent_verification'
        post 'fill_catlog'
        post 'add_absent_student'
        post 'remove_absent_student'
        post 'update'
        post 'publish_absenty'
      end
    end
    resources :exams, except: [:update] do
      member do
        get 'get_catlogs'
        get 'verify_exam'
        get "get_activities"
        get 'exam_conducted'
        get 'get_exam_info'
        get 'get_descendants'
        get 'group_exam_report'
        get 'manage_points'
        get 'get_chapters_points'
        post 'save_exam_points'
        post 'remove_exam_result'
        post 'update'
        post 'add_absunt_students'
        post 'add_absunt_student'
        post 'add_ignored_student'
        post 'remove_ignored_student'
        post 'remove_absunt_student'
        post 'upload_paper'
        post 'add_exam_results'
        post 'verify_exam_result'
        post 'verify_exam_absenty'
        post 'publish_exam_result'
      end
      resources :exams, only: [:create]
    end
    
    delete "students/:student_id" => "jkci_classes#remove_student_from_class"
  end

  resources :time_tables, only: [] do
    collection do 
      get 'calender_index'
    end
    resources :time_table_classes, only: [:create, :index, :update, :destroy] do
      member do
        post "assign_teacher"
      end
    end
    
  end

  resources :chapters, only: [:index] do
    member do
      get 'get_points'
    end
  end

  resources :holidays do
    collection do 
      get 'get_classes'
    end
  end
  
  resources :hostels do
    member do 
      get "get_unallocated_students"
      get 'get_logs'
    end
    
    resources :students, only: [] do
      get "get_other_rooms"
      post "change_room"
      post "swap_room_student"
      get 'get_hostel_students'
    end
    
    resources :hostel_rooms, only: [:index, :edit, :create, :update, :destroy] do
      member do
        get "allocate_students"
      end
    end
  end
  
  resources :contacts#, only: [:create]
  get '/organisation_profile' => "organisations#show"
  get '/organisation_edit' => "organisations#edit"
  post '/update_organisation' => "organisations#update"
  get '/organisations/cources' => "organisations#organisation_cources"
  get 'organisations/get_classes' => "organisations#organisation_classes"
  get 'organisations/absenty_graph_report' => "organisations#absenty_graph_report"
  get 'organisations/exams_graph_report' => "organisations#exams_graph_report"
  get 'organisations/off_class_graph_report' => "organisations#off_class_graph_report"
  get 'organisations/get_class_rooms' => "organisations#get_class_rooms"
  get 'organisations/organisation_standards' => "organisations#organisation_standards"
  get 'organisations/standard/:standard_id/remaining_organisations' => "organisations#remaining_standard_organisations"
  get 'organisations/standard/:standard_id/disable_standard' => "organisations#disable_organisation_standard"
  get 'organisations/standard/:standard_id/enable_standard' => "organisations#enable_organisation_standard"
  get '/remaining_cources' => "organisations#remaining_cources"
  get '/organisations/get_sub_organisations' => "organisations#sub_organisations_list"
  get '/organisations/add_standards' => "organisations#add_standards"
  get '/organisations/get_clerks' => "organisations#get_clerks"
  get '/organisations/clerks/:clerk_id/edit' => "organisations#edit_clerks"
  get '/organisations/users/:user_id/get_roles' => "organisations#get_clerk_roles"
  get "/organisations/users/:user_id/toggleEnable" => "organisations#toggle_enable_users"
  get "/organisations/get_standards" => "organisations#get_organisation_standards"
  get "/organisations/courses/:course_id/get_fee" => "organisations#get_standard_fee"
  get "/organisations/classes/:class_id/get_fee" => "organisations#get_class_fee"
  get "/organisation/get_last_attendances" => "organisations#get_last_attendances"
  post '/organisations/clerks/:clerk_id/update' => "organisations#update_clerks"
  post "/organisation/add_attendances" => "organisations#add_attendances"
  post "/organisations/courses/:course_id/update_fee" => "organisations#update_standard_fee"
  post "/organisations/classes/:class_id/update_fee" => "organisations#update_class_fee"
  post "/organisations/switch_organisation_standard" => "organisations#switch_organisation_standard"

app/controllers/register_organisations_controller.rb
class RegisterOrganisationsController < ApplicationController
  skip_before_filter :authenticate_with_token!, only: [:new, :create, :destroy, :sms_confirmation, :verify_confirmation]
  skip_before_filter :verify_authenticity_token, only: [:new, :create, :destroy, :sms_confirmation, :verify_confirmation]
  skip_before_filter :require_no_authentication, :only => [ :new, :create, :cancel, :sms_confirmation, :verify_confirmation ]
  http_basic_authenticate_with name: ORG_CREATE_U_NAME, password: ORG_CREATE_U_PASSWORD
  
  def new
    @register_organisation = TemporaryOrganisation.new
  end
  
  def create
    @register_organisation = TemporaryOrganisation.new(create_params.slice(:name, :email, :mobile, :short_name, :user_email))
    org_emails = Organisation.select([:email]).roots.map(&:email)
    if org_emails.include? @register_organisation.email 
      @register_organisation.errors.add(:email, "Email allready registered. Please contact eracoed admin.")
      render :new
      return 0
    end

    user = User.where(email: create_params[:user_email]).first 
    if user && user.valid_password?(params[:temporary_organisation][:password])
      if user.has_role? :creator
        if @register_organisation.save
          @register_organisation.generate_code(user)
          redirect_to sms_confirmation_register_organisation_path(@register_organisation.id_hash)
        else
          render :new
        end
      else
        flash[:notice] = "You are not authorised for add Organisation"
        redirect_to root_url
      end
    else
      render :new
    end
  end

  def sms_confirmation
    @register_organisation = TemporaryOrganisation.where(id_hash: params[:id]).first
    if @register_organisation.present? && !@register_organisation.is_confirmed
      
    else
      flash[:notice] = "Something went wrong please contact admin."
      redirect_to root_url
    end
  end

  def verify_confirmation
    @register_organisation = TemporaryOrganisation.where(id_hash: params[:id]).first
    if @register_organisation && @register_organisation.user_sms_code == params[:temporary_organisation][:sms_code] 
      @register_organisation.create_organisation if !@register_organisation.is_confirmed
      flash[:notice] = "Successfully verified. Please check client's Email"
      redirect_to root_url
    else
      @register_organisation.errors.add(:sms_code, " must match.")
      render :sms_confirmation
    end
  end
  
  protected
  def create_params
    params.require(:temporary_organisation).permit(:name, :email, :mobile, :short_name, :user_email, :password)
  end
end

app/helpers/register_organisation_helper.rb
module RegisterOrganisationHelper
end

app/views/register_organisations/new.html.erb
<%= render "layouts/header"%>
<div class="container">
  <h1>Register New Organisation</h1>
  <div class="col-sm-4" style="margin-bottom:50px;">
    <%= simple_form_for @register_organisation, :url => register_organisations_path  do |f| %>
    
    <%= f.input :name, placeholder: 'Name', required: true %>
    <%= f.input :email, placeholder: 'Name', required: true %>
    <%= f.input :mobile, placeholder: 'Name', required: true %>
    <%= f.input :short_name, placeholder: 'Name', required: true %>
    <%= f.input :user_email, placeholder: 'Name', required: true %>
    <div class="form-group email required temporary_organisation_user_email">
      <label class="email optional control-label" for="temporary_organisation_user_email">User Password</label>
      <%= password_field_tag :password, '' , class: "string email optional form-control", name: "temporary_organisation[password]", id: "temporary_organisation_user_password",  required: true%>
    </div>
    <%= f.button :submit, 'Create Organisation', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/register_organisations/sms_confirmation.html.erb
<header id="header">
  <nav id="main-nav" class="navbar navbar-default navbar-fixed-top" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand slientLink" href="/"><span style="font-size: 35px;color: #FFF;line-height: 1em;font-weight: bold;">EraCord</span></a>
      </div>
    </div>
    <!--/.container-->
  </nav>
  <!--/nav-->
</header>
<div class="container">
  <h1>New Organisation Sms Confirmation</h1>
  <div class="col-sm-12" style="padding-bottom:30px;">
    <div class="col-sm-4">
      Name
    </div>
    <div class="col-sm-8">
      <strong><%= @register_organisation.name %></strong>
    </div>
    <div class="col-sm-4">
      Email
    </div>
    <div class="col-sm-8">
      <strong><%= @register_organisation.email %></strong>
    </div>
    <div class="col-sm-4">
      Mobile
    </div>
    <div class="col-sm-8">
      <strong><%= @register_organisation.mobile %></strong>
    </div>
    <div class="col-sm-4">
      Short Name
    </div>
    <div class="col-sm-8">
      <strong><%= @register_organisation.short_name %></strong>
    </div>
  </div>
  <hr style="text-align:center; margin: 0 auto;width:80%;">
  <div class="col-sm-4" style="margin-top:30px;">
    <%= simple_form_for @register_organisation, :url => verify_confirmation_register_organisation_path(@register_organisation.id_hash), method: :post  do |f| %>
    <ul>
      <% @register_organisation.errors.full_messages.each do |msg| %>
      <li class="bg-danger"><%= msg %></li>
      <% end %>
    </ul>
    <div class="form-group email required temporary_organisation_user_email <%= 'has-error' if @register_organisation.errors.present? %>" >
      <label class="sms_code optional control-label" for="temporary_organisation_sms_code">Sms Code</label>
      <%= password_field_tag :sms_code, '' , class: "string email optional form-control", name: "temporary_organisation[sms_code]", id: "temporary_organisation_sms_code",  required: true %>
    </div>
    
    <%= f.button :submit, 'Verify Sms Code', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>